"""
polarticks — Polars-native technical analysis indicator library.

Import from the top-level package for convenience:

    from polarticks import sma, ema, rsi, atr, bollinger_bands
    from polarticks import crossover, is_bullish_engulfing, vwap

Or import from the specific module for clarity:

    from polarticks.momentum import rsi, stoch_rsi, fisher_transform
    from polarticks.volatility import atr, chandelier_exit, parkinson
    from polarticks.trend import ichimoku, elder_ray
"""

from polarticks.levels import (
    fibonacci_retracement,
    pivot_points_camarilla,
    pivot_points_demark,
    pivot_points_fibonacci,
    pivot_points_floor,
    pivot_points_woodie,
)
from polarticks.momentum import (
    cci,
    cmf,
    cmo,
    coppock,
    dpo,
    fisher_transform,
    kst,
    macd,
    mfi,
    ppo,
    roc,
    rsi,
    stoch_rsi,
    stochastic,
    tsi,
    ultimate_oscillator,
    williams_r,
)
from polarticks.moving_averages import (
    alma,
    dema,
    ema,
    hma,
    kama,
    mcginley_dynamic,
    sma,
    t3,
    tema,
    trix,
    vwma,
    wilder_smooth,
    wma,
    zlema,
)
from polarticks.patterns import (
    is_abandoned_baby_bearish,
    is_abandoned_baby_bullish,
    is_bearish_engulfing,
    is_bearish_harami,
    is_bullish_engulfing,
    is_bullish_harami,
    is_doji,
    is_evening_star,
    is_inside_bar,
    is_morning_star,
    is_pin_bar_bearish,
    is_pin_bar_bullish,
    is_three_black_crows,
    is_three_white_soldiers,
)
from polarticks.trend import (
    adx,
    aroon,
    donchian_channels,
    elder_ray,
    ichimoku,
    linreg_slope,
    parabolic_sar,
    stc,
    supertrend,
    vortex,
)
from polarticks.utils import (
    crossover,
    crossunder,
    log_returns,
    percent_rank,
    rolling_highest,
    rolling_lowest,
    rolling_std,
    simple_returns,
)
from polarticks.volatility import (
    atr,
    bollinger_bands,
    chaikin_volatility,
    chandelier_exit,
    garman_klass,
    historical_volatility,
    keltner_channels,
    mass_index,
    natr,
    parkinson,
    true_range,
    ulcer_index,
    williams_vix_fix,
    yang_zhang,
)
from polarticks.volume import ad_line, eom, force_index, kvo, nvi, obv, pvi, pvt, vwap, vwap_bands

__all__ = [
    # Moving averages
    "sma",
    "ema",
    "wma",
    "wilder_smooth",
    "dema",
    "tema",
    "hma",
    "vwma",
    "mcginley_dynamic",
    "kama",
    "trix",
    "zlema",
    "t3",
    "alma",
    # Momentum
    "rsi",
    "macd",
    "stochastic",
    "stoch_rsi",
    "ppo",
    "williams_r",
    "cci",
    "roc",
    "mfi",
    "cmf",
    "tsi",
    "ultimate_oscillator",
    "cmo",
    "dpo",
    "kst",
    "coppock",
    "fisher_transform",
    # Volatility
    "true_range",
    "atr",
    "natr",
    "bollinger_bands",
    "keltner_channels",
    "chaikin_volatility",
    "chandelier_exit",
    "historical_volatility",
    "ulcer_index",
    "mass_index",
    "parkinson",
    "garman_klass",
    "yang_zhang",
    "williams_vix_fix",
    # Trend
    "donchian_channels",
    "adx",
    "supertrend",
    "parabolic_sar",
    "ichimoku",
    "aroon",
    "vortex",
    "linreg_slope",
    "stc",
    "elder_ray",
    # Volume
    "vwap",
    "vwap_bands",
    "obv",
    "ad_line",
    "kvo",
    "eom",
    "pvt",
    "force_index",
    "nvi",
    "pvi",
    # Levels
    "pivot_points_floor",
    "pivot_points_camarilla",
    "pivot_points_fibonacci",
    "pivot_points_woodie",
    "pivot_points_demark",
    "fibonacci_retracement",
    # Patterns
    "is_bullish_engulfing",
    "is_bearish_engulfing",
    "is_pin_bar_bullish",
    "is_pin_bar_bearish",
    "is_inside_bar",
    "is_doji",
    "is_three_white_soldiers",
    "is_three_black_crows",
    "is_morning_star",
    "is_evening_star",
    "is_bullish_harami",
    "is_bearish_harami",
    "is_abandoned_baby_bullish",
    "is_abandoned_baby_bearish",
    # Utils
    "crossover",
    "crossunder",
    "log_returns",
    "simple_returns",
    "rolling_highest",
    "rolling_lowest",
    "rolling_std",
    "percent_rank",
]
